#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php');

if (isset($_ENV['APP_PATH'])) {
    $status->useAppPath($_ENV['APP_PATH']);
}

exit($status->handleCommand(new ArgvInput));
